apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-hss-config
  namespace: open5gs
  labels:
    epc-mode: hss
data:
  hss.yaml: |
    db_uri: {{ .Values.mongo.uri }}
    
    logger:
        file: /var/log/open5gs/hss.log
    
    parameter:
    
    hss:
        freeDiameter: /open5gs/config-map/diameter-hss.conf        