apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-mme-config
  namespace: open5gs
  labels:
    epc-mode: mme
data:
  mme.yaml: |
    logger:
        file: /var/log/open5gs/mme.log

    parameter:

    mme:
        freeDiameter: /open5gs/config-map/diameter-mme.conf
        s1ap:
           dev: net1
        gtpc:
           dev: net1
        gummei:
          plmn_id:
            mcc: {{ .Values.mme.mcc }}
            mnc: {{ .Values.mme.mnc }}
          mme_gid: 2
          mme_code: 1
        tai:
          plmn_id:
            mcc: {{ .Values.mme.mcc }}
            mnc: {{ .Values.mme.mnc }}
          tac: {{ .Values.mme.tac }}
        security:
            integrity_order : [ EIA1, EIA2, EIA0 ]
            ciphering_order : [ EEA0, EEA1, EEA2 ]
        network_name:
            full: Open5GS

    sgwc:
        gtpc:
          - name: s11.sgwc.open5gs.service
    smf:
      gtpc:
        - name: s5.smf.open5gs.service    
