apiVersion: v1
kind: Service
metadata:
  name: open5gs-webui
  namespace: open5gs
  labels:
    epc-mode: webui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    epc-mode: webui
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-webui
  namespace: open5gs  
  labels:
    epc-mode: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: webui
  template:
    metadata:
      labels:
        epc-mode: webui
    spec:
      nodeSelector:
        nodegroup: control-plane    
      containers:
      - name: webui
        imagePullPolicy: {{ .Values.webui.image.pullPolicy }}
        image: "{{ .Values.webui.image.repository }}:{{ .Values.webui.image.tag }}"
        volumeMounts:
          - mountPath: "/root/"
            name: mongo-ca-cert
            readOnly: true        
        env:
        - name: DB_URI
          value: {{ .Values.mongo.uri }}
        - name: NODE_ENV
          value: "production"  
        - name: HOSTNAME
          value: '0.0.0.0'             
      volumes:
        - name: mongo-ca-cert
          secret:
            secretName: {{ .Values.mongo.caSecretName }}               