apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: srslte
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: srslte
  template:
    metadata:
      annotations:
          k8s.v1.cni.cncf.io/networks: '[  { "name": "ipvlan-multus-sub-2", "interface": "net1" },
                                           { "name": "ipvlan-multus-sub-1-up", "interface": "net2" }
                                        ]'    
      labels:
        epc-mode: srslte
    spec:
      nodeSelector:
        nodegroup: user-plane   
      containers:
      - name: srslte
        image: {{srsLTEImage}}
        securityContext:
          privileged: true     
        command: ["sleep"]
        args: [ "infinity" ]
        volumeMounts:
          - name: srslte-lte-config
            mountPath: /srsLTEconfig          
      volumes:
        - name: srslte-lte-config
          configMap:
            name: srslte-config