---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: multus-sec-ip-operator-acct
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: multus-sec-ip-operator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]  

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: multus-sec-ip-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multus-sec-ip-operator
subjects:
  - kind: ServiceAccount
    name: multus-sec-ip-operator-acct
    namespace: kube-system
